site_name: Scenario Service Docs

nav:
  - Home: index.md
  - API: api.md

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true
            separate_signature: true
            show_root_heading: true
            heading_level: 2
